<?php
// ============================================
// CRITICAL: Check if accessed properly
// ============================================
if (!isset($db)) {
    die('
        <div class="alert alert-danger">
            <h4>Access Error</h4>
            <p><strong>This module cannot be accessed directly.</strong></p>
            <p>Please access it through the Super Admin Dashboard:</p>
            <p class="mb-0">
                <a href="../superadmin_dashboard.php?module=doctor" class="btn btn-primary">
                    Go to Dashboard Doctors
                </a>
            </p>
        </div>
    ');
}

require_once dirname(__DIR__, 3) . '/classes/Doctor.php';
require_once dirname(__DIR__, 3) . '/classes/User.php';

$doctor = new Doctor($db);
$user   = new User($db);

// --- State Variables ---
$message            = '';
$userMessage        = '';
$user_type          = $_SESSION['user_type'] ?? 'superadmin';
$search             = $_GET['search_doctor'] ?? '';

// --- Variables for Auto-Generated Credentials Modal ---
$displayDoctorId    = '';
$submittedEmail     = '';
$autoGeneratedPassword = '';

// Password generator function
function generateRandomPassword($length = 10) {
    $chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%';
    return substr(str_shuffle($chars), 0, $length);
}

// --- Fetch Specializations ---
$specializations = [];
try {
    $stmt_spec = $db->query("SELECT SPEC_ID, SPEC_NAME FROM specialization ORDER BY SPEC_NAME");
    $specializations = $stmt_spec->fetchAll(PDO::FETCH_ASSOC);
} catch (Exception $e) {
    error_log("Failed to load specializations: " . $e->getMessage());
    $message = "Could not load specializations. Check database connection and 'specialization' table.";
}

if ($user_type !== 'superadmin') {
    echo '<div class="alert alert-danger">Access denied. Only Super Admin can access this module.</div>';
    return;
}

// Session messages
if (isset($_SESSION['success_message'])) {
    $message = $_SESSION['success_message'];
    unset($_SESSION['success_message']);
}
if (isset($_SESSION['user_message'])) {
    $userMessage = $_SESSION['user_message'];
    unset($_SESSION['user_message']);
}

// ============================================
// HANDLE POST ACTIONS
// ============================================
if ($_SERVER['REQUEST_METHOD'] === 'POST') {

    // --- ADD NEW DOCTOR ---
    if (isset($_POST['add'])) {
        $data = [
            'doc_first_name'  => trim($_POST['doc_first_name']),
            'doc_middle_init' => trim($_POST['doc_middle_init']),
            'doc_last_name'   => trim($_POST['doc_last_name']),
            'doc_contact_num' => trim($_POST['doc_contact_num']),
            'doc_email'       => trim($_POST['doc_email']),
            'spec_id'         => $_POST['spec_id']
        ];

        $result = $doctor->create($data);

        if (is_numeric($result) && $result > 0) {
            $displayDoctorId = $result;
            $submittedEmail  = $data['doc_email'];
            $message = "Doctor added successfully with ID: {$displayDoctorId}.";

            if (!empty($submittedEmail)) {
                $autoGeneratedPassword = generateRandomPassword(10);
                $hashedPassword = password_hash($autoGeneratedPassword, PASSWORD_DEFAULT);

                $userData = [
                    'user_name' => $submittedEmail,
                    'password'  => $hashedPassword,
                    'linked_id' => $displayDoctorId,
                    'user_type' => 'doctor'
                ];

                $userCreationResult = $user->addLinkedAccount($userData);

                if ($userCreationResult === true || (is_string($userCreationResult) && stripos($userCreationResult, 'success') !== false)) {
                    $userMessage = "User account created for {$submittedEmail} with temporary password: <strong>{$autoGeneratedPassword}</strong>";
                } elseif (is_string($userCreationResult) && (stripos($userCreationResult, 'exists') !== false || stripos($userCreationResult, 'duplicate') !== false)) {
                    $message .= " But email already exists — user account not created.";
                    $autoGeneratedPassword = '';
                } else {
                    $message .= " But failed to create user account.";
                    $autoGeneratedPassword = '';
                }
            }
        } else {
            $message = (is_string($result) && stripos($result, 'DUPLICATE_CONTACT_NUMBER') !== false)
                ? "Failed: Contact number already registered."
                : "Failed to add doctor. Email or contact may already exist.";
        }
    }

    // --- UPDATE DOCTOR ---
    elseif (isset($_POST['update'])) {
        $data = [
            'doc_id'          => $_POST['doc_id'],
            'doc_first_name'  => trim($_POST['doc_first_name']),
            'doc_middle_init' => trim($_POST['doc_middle_init']),
            'doc_last_name'   => trim($_POST['doc_last_name']),
            'doc_contact_num' => trim($_POST['doc_contact_num']),
            'doc_email'       => trim($_POST['doc_email']),
            'spec_id'         => $_POST['spec_id']
        ];

        $result = $doctor->update($data);

        $_SESSION['success_message'] = ($result !== false && $result > 0)
            ? "Doctor ID {$data['doc_id']} updated successfully."
            : "No changes made for Doctor ID {$data['doc_id']}.";

        // FIXED: Correct redirect to superadmin_dashboard.php (this was the white screen cause)
        $redirect = "superadmin_dashboard.php?module=doctor";
        if (!empty($search)) {
            $redirect .= "&search_doctor=" . urlencode($search);
        }
        header("Location: $redirect");
        exit();
    }

    // --- DELETE DOCTOR ---
    elseif (isset($_POST['delete'])) {
        $id = $_POST['delete'];
        $success = $doctor->delete($id);
        $user->deleteLinkedAccount($id, 'doctor');

        $_SESSION['success_message'] = $success
            ? "Doctor ID {$id} deleted successfully."
            : "Failed to delete Doctor ID {$id}.";

        // FIXED: Same correct redirect
        $redirect = "superadmin_dashboard.php?module=doctor";
        if (!empty($search)) {
            $redirect .= "&search_doctor=" . urlencode($search);
        }
        header("Location: $redirect");
        exit();
    }
}

// ============================================
// FETCH DOCTORS
// ============================================
try {
    $records = !empty($search)
        ? $doctor->searchWithAppointments($search)
        : $doctor->all();
} catch (Exception $e) {
    $records = [];
    $message = "Error loading doctors: " . $e->getMessage();
}
?>

<h1 class="fw-bold mb-4">Doctor Management</h1>

<?php if ($message): ?>
<div class="alert <?= (stripos($message, 'Fail') !== false || stripos($message, 'Error') !== false) ? 'alert-danger' : 'alert-success' ?> alert-dismissible fade show">
    <?= htmlspecialchars($message) ?>
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
</div>
<?php endif; ?>

<?php if ($userMessage): ?>
<div class="alert alert-success alert-dismissible fade show">
    <?= $userMessage ?>
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
</div>
<?php endif; ?>

<div class="d-flex justify-content-between align-items-center mb-4 p-3 bg-white rounded-3 shadow-sm border">
    <form class="d-flex w-50" method="GET">
        <input type="hidden" name="module" value="doctor">
        <input id="search_doctor" class="form-control me-2 rounded-pill border-primary" type="search" name="search_doctor" placeholder="Search by name, contact, or specialization..." value="<?= htmlspecialchars($search) ?>">
        <button class="btn btn-outline-primary" type="submit">Search</button>
        <?php if ($search): ?>
            <a href="?module=doctor" class="btn btn-outline-secondary ms-2 rounded-pill">Reset</a>
        <?php endif; ?>
    </form>
    <button class="btn btn-success" data-bs-toggle="collapse" data-bs-target="#addFormDoctor">Add New Doctor</button>
</div>

<!-- ADD NEW DOCTOR FORM -->
<div id="addFormDoctor" class="collapse mb-4">
    <div class="card card-body shadow-sm border rounded bg-light">
        <form method="POST" class="row g-3" onsubmit="return validateDoctorForm(this)">
            <div class="col-md-4">
                <label class="form-label fw-semibold">First Name *</label>
                <input type="text" name="doc_first_name" class="form-control" placeholder="First Name" required>
            </div>
            <div class="col-md-4">
                <label class="form-label fw-semibold">Middle Initial</label>
                <input type="text" name="doc_middle_init" class="form-control" placeholder="M.I." maxlength="1">
            </div>
            <div class="col-md-4">
                <label class="form-label fw-semibold">Last Name *</label>
                <input type="text" name="doc_last_name" class="form-control" placeholder="Last Name" required>
            </div>
            <div class="col-md-4">
                <label class="form-label fw-semibold">Contact Number *</label>
                <input type="text" name="doc_contact_num" class="form-control" placeholder="09xxxxxxxxx" pattern="^09\d{9}$" required>
            </div>
            <div class="col-md-4">
                <label class="form-label fw-semibold">Email *</label>
                <input type="email" name="doc_email" class="form-control" placeholder="doctor@example.com" required>
            </div>
            <div class="col-md-4">
                <label class="form-label fw-semibold">Specialization *</label>
                <select name="spec_id" class="form-select" required>
                    <option value="">-- Select Specialization --</option>
                    <?php foreach ($specializations as $spec): ?>
                        <option value="<?= $spec['SPEC_ID'] ?>"><?= htmlspecialchars($spec['SPEC_NAME']) ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="col-12 text-end">
                <button type="submit" name="add" class="btn btn-primary btn-lg">Save Doctor & Create User Account</button>
            </div>
        </form>
    </div>
</div>

<!-- DOCTORS TABLE -->
<div class="card p-3 shadow-sm">
    <h5>Doctor Records (Total: <?= count($records) ?>)</h5>

    <?php if (empty($records)): ?>
        <div class="alert alert-warning mt-3">
            No doctors found<?= $search ? ' matching "' . htmlspecialchars($search) . '"' : '' ?>.
        </div>
    <?php else: ?>
    <div class="table-responsive">
        <table class="table table-bordered table-striped align-middle mt-3">
            <thead class="table-light">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Contact</th>
                    <th>Email</th>
                    <th>Specialization</th>
                    <th>Created</th>
                    <th>Updated</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($records as $r): ?>
                <tr>
                    <!-- Hidden form for this row -->
                    <form method="POST" id="doctorForm_<?= $r['doc_id'] ?>" class="d-none">
                        <input type="hidden" name="doc_id" value="<?= $r['doc_id'] ?>">
                        <input type="hidden" name="doc_first_name" value="<?= htmlspecialchars($r['doc_first_name']) ?>">
                        <input type="hidden" name="doc_middle_init" value="<?= htmlspecialchars($r['doc_middle_init'] ?? '') ?>">
                        <input type="hidden" name="doc_last_name" value="<?= htmlspecialchars($r['doc_last_name']) ?>">
                        <input type="hidden" name="doc_contact_num" value="<?= htmlspecialchars($r['doc_contact_num']) ?>">
                        <input type="hidden" name="doc_email" value="<?= htmlspecialchars($r['doc_email']) ?>">
                        <input type="hidden" name="spec_id" value="<?= $r['spec_id'] ?>">
                    </form>

                    <td class="fw-semibold"><?= $r['doc_id'] ?></td>
                    <td>
                        <input form="doctorForm_<?= $r['doc_id'] ?>" name="doc_first_name" value="<?= htmlspecialchars($r['doc_first_name']) ?>" class="form-control form-control-sm mb-1" required>
                        <input form="doctorForm_<?= $r['doc_id'] ?>" name="doc_middle_init" value="<?= htmlspecialchars($r['doc_middle_init'] ?? '') ?>" class="form-control form-control-sm mb-1" maxlength="1">
                        <input form="doctorForm_<?= $r['doc_id'] ?>" name="doc_last_name" value="<?= htmlspecialchars($r['doc_last_name']) ?>" class="form-control form-control-sm" required>
                    </td>
                    <td>
                        <input form="doctorForm_<?= $r['doc_id'] ?>" name="doc_contact_num" value="<?= htmlspecialchars($r['doc_contact_num']) ?>" class="form-control form-control-sm" pattern="^09\d{9}$" required>
                    </td>
                    <td>
                        <input form="doctorForm_<?= $r['doc_id'] ?>" name="doc_email" value="<?= htmlspecialchars($r['doc_email']) ?>" class="form-control form-control-sm" type="email" required>
                    </td>
                    <td>
                        <select form="doctorForm_<?= $r['doc_id'] ?>" name="spec_id" class="form-select form-select-sm" required>
                            <?php foreach ($specializations as $spec): ?>
                                <option value="<?= $spec['SPEC_ID'] ?>" <?= ($r['spec_id'] == $spec['SPEC_ID']) ? 'selected' : '' ?>>
                                    <?= htmlspecialchars($spec['SPEC_NAME']) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <td class="small text-muted"><?= $r['formatted_created_at'] ?? '-' ?></td>
                    <td class="small text-muted"><?= $r['formatted_updated_at'] ?? '-' ?></td>
                    <td class="text-center">
                        <button form="doctorForm_<?= $r['doc_id'] ?>" name="update" class="btn btn-sm btn-success mb-1 w-100">Update</button>
                        <button form="doctorForm_<?= $r['doc_id'] ?>" name="delete" value="<?= $r['doc_id'] ?>" class="btn btn-sm btn-danger mb-1 w-100"
                            onclick="return confirm('Delete Dr. <?= htmlspecialchars($r['doc_first_name'] . ' ' . $r['doc_last_name']) ?>? This will also delete the linked account.')">
                            Delete
                        </button>
                        <a href="?module=appointment&doc_id=<?= $r['doc_id'] ?>" class="btn btn-sm btn-info mb-1 w-100">Appointments</a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php endif; ?>
</div>

<!-- CREDENTIALS MODAL -->
<div class="modal fade" id="autoUserDoctorModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bg-success text-white">
                <h5 class="modal-title">New Doctor Account Created!</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <p class="lead">Doctor and user account created successfully.</p>
                <p class="text-danger"><strong>Save these credentials now — password will not show again.</strong></p>
                <div class="mb-3">
                    <label class="form-label fw-bold">Doctor ID</label>
                    <input type="text" class="form-control" value="<?= htmlspecialchars($displayDoctorId) ?>" readonly>
                </div pí>
                <div class="mb-3">
                    <label class="form-label fw-bold">Username (Email)</label>
                    <input type="text" class="form-control" value="<?= htmlspecialchars($submittedEmail) ?>" readonly>
                </div>
                <div class="mb-3">
                    <label class="form-label fw-bold">Temporary Password</label>
                    <div class="input-group">
                        <input type="text" id="tempPasswordDoctor" class="form-control" value="<?= htmlspecialchars($autoGeneratedPassword) ?>" readonly>
                        <button class="btn btn-outline-secondary" type="button" onclick="copyPassword()">Copy</button>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">I've Saved It</button>
            </div>
        </div>
    </div>
</div>

<script>
function validateDoctorForm(f) {
    const email = f.doc_email.value.trim();
    const contact = f.doc_contact_num.value;

    if (!/^[^@]+@[^@]+\.[a-z]+$/i.test(email)) {
        alert("Please enter a valid email address.");
        return false;
    }
    if (!/^09\d{9}$/.test(contact)) {
        alert("Contact must be 11 digits starting with 09 (e.g., 09123456789)");
        return false;
    }
    return true;
}

function copyPassword() {
    const el = document.getElementById('tempPasswordDoctor');
    el.select();
    document.execCommand('copy');
    alert('Password copied!');
}

// Show modal if new doctor was added
<?php if ($displayDoctorId && $autoGeneratedPassword): ?>
document.addEventListener("DOMContentLoaded", () => {
    new bootstrap.Modal(document.getElementById('autoUserDoctorModal')).show();
});
<?php endif; ?>
</script>