<?php
// ============================================
// ON-SCREEN DEBUGGER - START
// ============================================
error_reporting(E_ALL);
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);

// Debug output buffer
$debugOutput = [];

function debugLog($message, $data = null) {
    global $debugOutput;
    $timestamp = date('H:i:s');
    $entry = [
        'time' => $timestamp,
        'message' => $message,
        'data' => $data
    ];
    $debugOutput[] = $entry;
}

debugLog("=== DOCTOR MODULE DEBUG STARTED ===");
debugLog("REQUEST METHOD", $_SERVER['REQUEST_METHOD']);
debugLog("GET PARAMETERS", $_GET);
debugLog("POST PARAMETERS", isset($_POST['add']) || isset($_POST['update']) || isset($_POST['delete']) ? 'Form submitted' : 'No form submission');
debugLog("SESSION USER TYPE", $_SESSION['user_type'] ?? 'NOT SET');

// Check database connection
debugLog("Checking database connection...");
if (!isset($db)) {
    debugLog("❌ ERROR: Database connection NOT SET");
    die('
        <div class="alert alert-danger">
            <h4><i class="bi bi-exclamation-triangle"></i> Access Error</h4>
            <p><strong>This module cannot be accessed directly.</strong></p>
            <p>Database connection is not initialized.</p>
            <p class="mb-0">
                <a href="../superadmin_dashboard.php?module=doctor" class="btn btn-primary">
                    Go to Dashboard &rarr; Doctors
                </a>
            </p>
        </div>
    ');
} else {
    debugLog("✅ Database connection EXISTS", get_class($db));
    
    // Test database connection
    try {
        $testQuery = $db->query("SELECT 1 as test");
        $testResult = $testQuery->fetch();
        debugLog("✅ Database test query SUCCESS", $testResult);
    } catch (Exception $e) {
        debugLog("❌ Database test query FAILED", $e->getMessage());
    }
    
    // Test doctor table
    try {
        $tableCheck = $db->query("SELECT COUNT(*) as count FROM doctor");
        $tableResult = $tableCheck->fetch();
        debugLog("✅ Doctor table accessible", "Total doctors in DB: " . $tableResult['count']);
    } catch (Exception $e) {
        debugLog("❌ Doctor table check FAILED", $e->getMessage());
    }
}
// ============================================
// ON-SCREEN DEBUGGER - END
// ============================================

// ============================================
// CRITICAL: Check if accessed properly
// ============================================
if (!isset($db)) {
    die('
        <div class="alert alert-danger">
            <h4><i class="bi bi-exclamation-triangle"></i> Access Error</h4>
            <p><strong>This module cannot be accessed directly.</strong></p>
            <p>Please access it through the Super Admin Dashboard:</p>
            <p class="mb-0">
                <a href="../superadmin_dashboard.php?module=doctor" class="btn btn-primary">
                    Go to Dashboard &rarr; Doctors
                </a>
            </p>
        </div>
    ');
}

debugLog("Loading required classes...");
require_once dirname(__DIR__, 3) . '/classes/Doctor.php';
require_once dirname(__DIR__, 3) . '/classes/User.php';

debugLog("Initializing Doctor and User classes...");
try {
    $doctor = new Doctor($db);
    $user = new User($db);
    debugLog("✅ Classes initialized successfully");
} catch (Exception $e) {
    debugLog("❌ ERROR initializing classes", $e->getMessage());
    die("Fatal error: " . $e->getMessage());
}

// --- State Variables ---
$message = '';
$userMessage = '';
$user_type = $_SESSION['user_type'] ?? 'superadmin';
$search = $_GET['search_doctor'] ?? '';

debugLog("State variables", [
    'user_type' => $user_type,
    'search_term' => $search ? $search : 'EMPTY'
]);

// --- Variables for Auto-Generated Credentials Modal ---
$displayDoctorId = '';
$submittedEmail = '';
$autoGeneratedPassword = '';
// ---------------------------------------------------

// Password generator function
function generateRandomPassword($length = 10) {
    $chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%';
    return substr(str_shuffle($chars), 0, $length);
}

// --- Fetch Specializations ---
debugLog("Fetching specializations from database...");
$specializations = [];
try {
    $stmt_spec = $db->query("SELECT SPEC_ID, SPEC_NAME FROM specialization ORDER BY SPEC_NAME");
    $specializations = $stmt_spec->fetchAll(PDO::FETCH_ASSOC);
    debugLog("✅ Specializations loaded", "Count: " . count($specializations));
} catch (Exception $e) {
    debugLog("❌ FAILED to load specializations", $e->getMessage());
    error_log("Failed to load specializations: " . $e->getMessage());
    $message = "Could not load specializations. Check database connection and 'specialization' table.";
}

if ($user_type !== 'superadmin') {
    debugLog("❌ Access denied - user is not superadmin", $user_type);
    echo '<div class="alert alert-danger">Access denied. Only Super Admin can access this module.</div>';
    return;
}

// Check for session messages
if (isset($_SESSION['success_message'])) {
    $message = $_SESSION['success_message'];
    unset($_SESSION['success_message']);
    debugLog("Session success message retrieved", $message);
}
if (isset($_SESSION['user_message'])) {
    $userMessage = $_SESSION['user_message'];
    unset($_SESSION['user_message']);
    debugLog("Session user message retrieved", $userMessage);
}


// Handle actions
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    debugLog("📝 POST REQUEST DETECTED");

    // --- 1. Handle ADD (Create) Doctor ---
    if (isset($_POST['add'])) {
        debugLog("➕ ADD DOCTOR action triggered");
        $data = [
            'doc_first_name'  => trim($_POST['doc_first_name']),
            'doc_middle_init' => trim($_POST['doc_middle_init']),
            'doc_last_name'   => trim($_POST['doc_last_name']),
            'doc_contact_num' => trim($_POST['doc_contact_num']),
            'doc_email'       => trim($_POST['doc_email']),
            'spec_id'         => $_POST['spec_id']
        ];
        debugLog("Doctor data", $data);

        $result = $doctor->create($data);
        debugLog("Create result", ['result' => $result, 'type' => gettype($result)]);
        
        if (is_numeric($result) && $result > 0) {
            $displayDoctorId = $result;
            $submittedEmail = $data['doc_email'];
            $message = "Doctor added successfully with ID: {$displayDoctorId}.";
            debugLog("✅ Doctor created successfully", $displayDoctorId);

            if (!empty($submittedEmail)) { 
                $autoGeneratedPassword = generateRandomPassword(10);
                $hashedPassword = password_hash($autoGeneratedPassword, PASSWORD_DEFAULT);
                
                $userData = [
                    'user_name' => $submittedEmail,
                    'password'  => $hashedPassword,
                    'linked_id' => $displayDoctorId,
                    'user_type' => 'doctor'
                ];
                debugLog("Creating user account for", $submittedEmail);
                
                $userCreationResult = $user->addLinkedAccount($userData);
                debugLog("User creation result", $userCreationResult);
                
                if ($userCreationResult === true || (is_string($userCreationResult) && strpos($userCreationResult, '✅') !== false)) {
                    $userMessage = "User account created for {$submittedEmail} with temporary password: <strong>{$autoGeneratedPassword}</strong>";
                }
                elseif(is_string($userCreationResult) && (strpos($userCreationResult, 'exists') !== false || strpos($userCreationResult, 'duplicate') !== false || strpos($userCreationResult, 'Email already') !== false)) {
                    $message = "Doctor record ID {$displayDoctorId} was saved, but email already exists in the system.";
                    $autoGeneratedPassword = '';
                }
                else {
                    $message = "Doctor record ID {$displayDoctorId} was saved, but failed to create user account. Error: " . htmlspecialchars($userCreationResult);
                    $autoGeneratedPassword = '';
                }
            } else {
                $userMessage = "Doctor added successfully, but no email provided for user creation.";
                $autoGeneratedPassword = '';
            }

        } else {
            debugLog("❌ Failed to add doctor", $result);
            if (is_string($result) && strpos($result, 'DUPLICATE_CONTACT_NUMBER') !== false) {
                $message = "Failed to add doctor. The contact number " . htmlspecialchars($data['doc_contact_num']) . "** is already registered. Contact numbers must be unique.";
            } else {
                $message = "Failed to add doctor, email or contact number may already exist.";
            }
        }
    }
    
    // --- 2. Handle UPDATE Doctor ---
    elseif (isset($_POST['update'])) {
        debugLog("✏️ UPDATE DOCTOR action triggered");
        $data = [
            'doc_id'          => $_POST['doc_id'],
            'doc_first_name'  => trim($_POST['doc_first_name']),
            'doc_middle_init' => trim($_POST['doc_middle_init']),
            'doc_last_name'   => trim($_POST['doc_last_name']),
            'doc_contact_num' => trim($_POST['doc_contact_num']),
            'doc_email'       => trim($_POST['doc_email']),
            'spec_id'         => $_POST['spec_id']
        ];
        debugLog("Update data", $data);

        $result = $doctor->update($data);
        debugLog("Update result", $result);
        
        if ($result !== false && $result > 0) {
            $_SESSION['success_message'] = "Doctor ID {$data['doc_id']} updated successfully.";
        } else {
            $_SESSION['success_message'] = "Doctor ID {$data['doc_id']} - No changes detected or update failed.";
        }
        
        // Use proper redirect with full script path
        $redirectUrl = $_SERVER['SCRIPT_NAME'] . "?module=doctor";
        debugLog("Redirecting to", $redirectUrl);
        header("Location: " . $redirectUrl);
        exit();
    }

    // --- 3. Handle DELETE Doctor ---
    elseif (isset($_POST['delete'])) {
        debugLog("🗑️ DELETE DOCTOR action triggered");
        $id = $_POST['delete'];
        debugLog("Deleting doctor ID", $id);
        
        $success = $doctor->delete($id);
        $user->deleteLinkedAccount($id, 'doctor');
        debugLog("Delete result", $success);
        
        $_SESSION['success_message'] = $success 
            ? "Doctor ID {$id} deleted successfully." 
            : "Failed to delete doctor ID {$id}.";
        
        // Use proper redirect with full script path
        $redirectUrl = $_SERVER['SCRIPT_NAME'] . "?module=doctor";
        debugLog("Redirecting to", $redirectUrl);
        header("Location: " . $redirectUrl);
        exit();
    }
}

// Fetch doctor records
debugLog("📋 Fetching doctor records...");
debugLog("Search mode", !empty($search) ? "SEARCH: '$search'" : "ALL RECORDS");

try {
    if (!empty($search)) {
        debugLog("Calling searchWithAppointments()", $search);
        
        // TEST: Try direct SQL query to see what's in the database
        try {
            $testSql = "SELECT DOC_ID, DOC_FIRST_NAME, DOC_LAST_NAME FROM doctor WHERE DOC_FIRST_NAME LIKE :search OR DOC_LAST_NAME LIKE :search";
            $testStmt = $db->prepare($testSql);
            $testStmt->execute([':search' => '%' . $search . '%']);
            $testResults = $testStmt->fetchAll(PDO::FETCH_ASSOC);
            debugLog("🔬 DIRECT SQL TEST", "Found: " . count($testResults) . " doctors");
            if (count($testResults) > 0) {
                debugLog("Direct SQL Results", $testResults);
            }
        } catch (Exception $testEx) {
            debugLog("❌ Direct SQL test failed", $testEx->getMessage());
        }
        
        $records = $doctor->searchWithAppointments($search);
    } else {
        debugLog("Calling all()");
        $records = $doctor->all();
    }
    debugLog("✅ Records fetched", "Count: " . count($records));
    if (count($records) > 0) {
        debugLog("First record sample", $records[0]);
    }
} catch (Exception $e) {
    debugLog("❌ ERROR fetching doctor records", $e->getMessage());
    $records = [];
    $message = "Error loading doctor records: " . $e->getMessage();
}

debugLog("=== RENDERING HTML ===");

// Render Debug Panel
function renderDebugPanel() {
    global $debugOutput;
    ?>
    <div class="card mb-4 border-danger">
        <div class="card-header bg-danger text-white">
            <h5 class="mb-0"><i class="bi bi-bug"></i> 🔍 DEBUG PANEL (Remove in Production)</h5>
        </div>
        <div class="card-body" style="max-height: 400px; overflow-y: auto; font-family: monospace; font-size: 12px; background: #f8f9fa;">
            <?php foreach ($debugOutput as $entry): ?>
                <div class="mb-2 p-2 border-bottom">
                    <strong style="color: #0066cc;">[<?= $entry['time'] ?>]</strong>
                    <span style="color: #006600;"><?= htmlspecialchars($entry['message']) ?></span>
                    <?php if ($entry['data'] !== null): ?>
                        <pre style="margin: 5px 0 0 20px; padding: 10px; background: #fff; border-left: 3px solid #0066cc;"><?= htmlspecialchars(print_r($entry['data'], true)) ?></pre>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <?php
}
?>

<?php renderDebugPanel(); ?>

<h1 class="fw-bold mb-4">Doctor Management</h1>

<?php if ($message): ?>
<div class="alert <?= strpos($message, '❌') !== false || strpos($message, '⚠️') !== false ? 'alert-danger' : 'alert-success' ?> alert-dismissible fade show">
    <?= $message ?>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<?php endif; ?>

<?php if ($userMessage): ?>
<div class="alert <?= strpos($userMessage, '❌') !== false ? 'alert-danger' : 'alert-success' ?> alert-dismissible fade show">
    <?= $userMessage ?>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<?php endif; ?>

<div class="d-flex justify-content-between align-items-center mb-4 p-3 bg-white rounded-3 shadow-sm border">
    <form class="d-flex w-50" method="GET">
        <input type="hidden" name="module" value="doctor">
        <label for="search_doctor" class="visually-hidden">Search doctors</label>
        <input id="search_doctor" class="form-control me-2 rounded-pill border-primary" type="search" name="search_doctor" placeholder="Search by name, contact, or specialization..." value="<?= htmlspecialchars($search) ?>" aria-label="Search by name, contact, or specialization">
        <button class="btn btn-outline-primary" type="submit">Search</button>
        <?php if ($search): ?>
            <a href="?module=doctor" class="btn btn-outline-secondary ms-2 rounded-pill">Reset</a>
        <?php endif; ?>
    </form>
    <button class="btn btn-success" data-bs-toggle="collapse" data-bs-target="#addFormDoctor" aria-expanded="false" aria-controls="addFormDoctor">Add New Doctor</button>
</div>

<div id="addFormDoctor" class="collapse mb-4">
    <div class="card card-body shadow-sm border rounded bg-light">
        <form method="POST" class="row g-3" onsubmit="return validateDoctorForm(this)">
            <div class="col-md-4">
                <label for="doc_first_name" class="form-label fw-semibold">First Name *</label>
                <input id="doc_first_name" type="text" name="doc_first_name" class="form-control" placeholder="First Name" required>
            </div>
            <div class="col-md-4">
                <label for="doc_middle_init" class="form-label fw-semibold">Middle Initial</label>
                <input id="doc_middle_init" type="text" name="doc_middle_init" class="form-control" placeholder="M.I." maxlength="1">
            </div>
            <div class="col-md-4">
                <label for="doc_last_name" class="form-label fw-semibold">Last Name *</label>
                <input id="doc_last_name" type="text" name="doc_last_name" class="form-control" placeholder="Last Name" required>
            </div>
            <div class="col-md-4">
                <label for="doc_contact_num" class="form-label fw-semibold">Contact Number *</label>
                <input id="doc_contact_num" type="text" name="doc_contact_num" class="form-control" placeholder="09xxxxxxxxx" pattern="^09\d{9}$" required>
            </div>
            <div class="col-md-4">
                <label for="doc_email" class="form-label fw-semibold">Email *</label>
                <input id="doc_email" type="email" name="doc_email" class="form-control" placeholder="doctor@example.com" required>
            </div>
            <div class="col-md-4">
                <label for="spec_id" class="form-label fw-semibold">Specialization *</label>
                <select id="spec_id" name="spec_id" class="form-select" required>
                    <option value="">-- Select Specialization --</option>
                    <?php foreach ($specializations as $spec): ?>
                        <option value="<?= htmlspecialchars($spec['SPEC_ID']) ?>">
                            <?= htmlspecialchars($spec['SPEC_NAME']) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="col-12 text-end">
                <button type="submit" name="add" class="btn btn-primary btn-lg">Save Doctor & Create User Account</button>
            </div>
        </form>
    </div>
</div>

<div class="card p-3 shadow-sm">
    <h5>Doctor Records (Total: <?= count($records) ?>)</h5>
    <?php if (empty($records)): ?>
        <div class="alert alert-warning mt-3">
            <i class="bi bi-info-circle"></i> No doctors found<?= $search ? ' matching "' . htmlspecialchars($search) . '"' : '' ?>.
        </div>
    <?php else: ?>
    <div class="table-responsive">
        <table class="table table-bordered table-striped align-middle mt-3"> 
            <thead class="table-light">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Contact</th>
                    <th scope="col">Email</th>
                    <th scope="col">Specialization</th>
                    <th scope="col">Created</th>
                    <th scope="col">Updated</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($records as $r): ?>
                    <tr>
                        <form method="POST" onsubmit="return validateDoctorForm(this)">
                            <input type="hidden" name="doc_id" value="<?= $r['doc_id'] ?>">
                            <td class="fw-semibold"><?= $r['doc_id'] ?></td>
                            <td>
                                <label for="doc_first_name_<?= $r['doc_id'] ?>" class="visually-hidden">First Name</label>
                                <input id="doc_first_name_<?= $r['doc_id'] ?>" name="doc_first_name" value="<?= htmlspecialchars($r['doc_first_name']) ?>" class="form-control form-control-sm mb-1" placeholder="First" required>
                                <label for="doc_middle_init_<?= $r['doc_id'] ?>" class="visually-hidden">Middle Initial</label>
                                <input id="doc_middle_init_<?= $r['doc_id'] ?>" name="doc_middle_init" value="<?= htmlspecialchars($r['doc_middle_init']) ?>" class="form-control form-control-sm mb-1" placeholder="M.I." maxlength="1">
                                <label for="doc_last_name_<?= $r['doc_id'] ?>" class="visually-hidden">Last Name</label>
                                <input id="doc_last_name_<?= $r['doc_id'] ?>" name="doc_last_name" value="<?= htmlspecialchars($r['doc_last_name']) ?>" class="form-control form-control-sm" placeholder="Last" required>
                            </td>
                            <td>
                                <label for="doc_contact_num_<?= $r['doc_id'] ?>" class="visually-hidden">Contact Number</label>
                                <input id="doc_contact_num_<?= $r['doc_id'] ?>" name="doc_contact_num" value="<?= htmlspecialchars($r['doc_contact_num']) ?>" class="form-control form-control-sm" pattern="^09\d{9}$" required>
                            </td>
                            <td>
                                <label for="doc_email_<?= $r['doc_id'] ?>" class="visually-hidden">Email</label>
                                <input id="doc_email_<?= $r['doc_id'] ?>" name="doc_email" value="<?= htmlspecialchars($r['doc_email']) ?>" class="form-control form-control-sm" type="email" required>
                            </td>
                            <td>
                                <label for="spec_id_<?= $r['doc_id'] ?>" class="visually-hidden">Specialization</label>
                                <select id="spec_id_<?= $r['doc_id'] ?>" name="spec_id" class="form-select form-select-sm" required>
                                    <?php foreach ($specializations as $spec): ?>
                                        <option value="<?= htmlspecialchars($spec['SPEC_ID']) ?>" <?= ($r['spec_id'] == $spec['SPEC_ID']) ? 'selected' : '' ?>>
                                            <?= htmlspecialchars($spec['SPEC_NAME']) ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </td>
                            <td class="small text-muted"><?= $r['formatted_created_at'] ?? '-' ?></td>
                            <td class="small text-muted"><?= $r['formatted_updated_at'] ?? '-' ?></td>
                            <td class="text-center">
                                <button name="update" class="btn btn-sm btn-success mb-1 w-100">Update</button>
                                <button name="delete" value="<?= $r['doc_id'] ?>" class="btn btn-sm btn-danger mb-1 w-100" onclick="return confirm('Delete Dr. <?= htmlspecialchars($r['doc_first_name']) ?> <?= htmlspecialchars($r['doc_last_name']) ?>? This will also delete the linked user account.')">
                                    Delete
                                </button>
                                <a href="?module=appointment&doc_id=<?= $r['doc_id'] ?>" class="btn btn-sm btn-info mb-1 w-100" title="View Appointments">
                                    Appointments
                                </a>
                            </td>
                        </form>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php endif; ?>
</div>

<!-- Modal for displaying auto-generated credentials -->
<div class="modal fade" id="autoUserDoctorModal" tabindex="-1" aria-labelledby="autoUserDoctorModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered"><div class="modal-content">
        <div class="modal-header bg-success text-white">
            <h5 class="modal-title" id="autoUserDoctorModalLabel">New Doctor User Account Created!</h5>
            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <p class="lead">A new doctor record and linked user account were successfully created.</p>
            <p class="text-danger"><strong>Important:</strong> Please save these credentials securely. The password will not be shown again.</p>
            <div class="mb-3">
                <label for="modal_doctor_id" class="form-label fw-bold">Doctor ID</label>
                <input id="modal_doctor_id" type="text" class="form-control" value="<?= htmlspecialchars($displayDoctorId ?? '') ?>" readonly>
            </div>
            <div class="mb-3">
                <label for="modal_doctor_email" class="form-label fw-bold">Username (Email)</label>
                <input id="modal_doctor_email" type="text" class="form-control" value="<?= htmlspecialchars($submittedEmail ?? '') ?>" readonly>
            </div>
            <div class="mb-3">
                <label for="tempPasswordDoctor" class="form-label fw-bold">Temporary Password</label>
                <div class="input-group">
                    <input type="text" id="tempPasswordDoctor" class="form-control" value="<?= htmlspecialchars($autoGeneratedPassword) ?>" readonly>
                    <button class="btn btn-outline-secondary" type="button" onclick="copyPassword()" aria-label="Copy password">Copy</button>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">I've Saved the Credentials</button>
        </div>
    </div></div>
</div>

<script>
function validateDoctorForm(f) {
    const emailInput = f.querySelector('input[name="doc_email"]');
    if (emailInput && !/^[^@]+@[^@]+\.[a-z]+$/i.test(emailInput.value)) {
        alert("Invalid email format. Please enter a valid email address.");
        return false;
    }
    
    const contactInput = f.querySelector('input[name="doc_contact_num"]');
    if (contactInput && !/^09\d{9}$/.test(contactInput.value)) {
        alert("Invalid phone number format. Please use the format 09xxxxxxxxx (11 digits starting with 09).");
        return false;
    }

    return true;
}

function copyPassword() {
    const passwordInput = document.getElementById('tempPasswordDoctor');
    if (passwordInput) {
        passwordInput.select();
        document.execCommand('copy');
        alert('Password copied to clipboard!');
    }
}

<?php if($displayDoctorId && !empty($autoGeneratedPassword)): ?>
document.addEventListener("DOMContentLoaded", function() {
    setTimeout(function() {
        var modal = new bootstrap.Modal(document.getElementById('autoUserDoctorModal'));
        modal.show();
    }, 100);
});
<?php endif; ?>
</script>