<?php
// staff-module.php
require_once dirname(__DIR__, 3) . '/classes/Staff.php';
require_once dirname(__DIR__, 3) . '/classes/User.php'; // Required for linked user account creation

// NOTE: $db, $_SESSION['user_type'] (e.g., 'super_admin'), and formatDate() are assumed to be available.

$staff = new Staff($db);
$user = new User($db); // Assuming User class is available
$message = '';
$userMessage = '';
$user_type = $_SESSION['user_type'] ?? 'super_admin';
$search = $_GET['search_staff'] ?? '';
$newStaff = null;
$autoGeneratedPassword = '';
$displayStaffId = '';
$submittedEmail = '';

// --- ACCESS CONTROL ---
if ($user_type !== 'super_admin') {
    echo '<div class="alert alert-danger">Access denied. Only Super Admin can access this module.</div>';
    return;
}

// Helper function (assuming it's available)
// function formatDate($timestamp) { /* ... */ } 
function generateRandomPassword($length = 10) {
    return substr(str_shuffle('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'), 0, $length);
}


if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    
    // --- 1. Handle ADD (Create) Staff ---
    if (isset($_POST['add'])) {
        $data = [
            'first_name'    => trim($_POST['staff_first_name']),
            'middle_init'   => trim($_POST['staff_middle_init'] ?? ''),
            'last_name'     => trim($_POST['staff_last_name']),
            'phone'         => trim($_POST['staff_contact_num']),
            'email'         => trim($_POST['staff_email'] ?? '')
        ];
        
        // staffId will be the new ID (integer) on success, or an error string on failure
        $staffId = $staff->addStaff($data, $user_type); 

        // --- FIX IS HERE: Check for a valid positive integer ID ---
        if (is_numeric($staffId) && $staffId > 0) {
            // --- SUCCESS PATH ---
            $message = "✅ Staff added successfully with ID: {$staffId}.";
            $displayStaffId = $staffId;
            $submittedEmail = $data['email'];

            if (!empty($submittedEmail)) { 
                $autoGeneratedPassword = generateRandomPassword(10);
                $hashedPassword = password_hash($autoGeneratedPassword, PASSWORD_DEFAULT);
                
                $userData = [
                    'user_name' => $submittedEmail,
                    'password'  => $hashedPassword,
                    'linked_id' => $staffId, // Use the new Staff ID
                    'user_type' => 'staff'
                ];
                
                $userCreationResult = $user->addLinkedAccount($userData);
                
                if ($userCreationResult === true || (is_string($userCreationResult) && strpos($userCreationResult, '✅') !== false)) {
                    $userMessage = "✅ User account created for {$submittedEmail} with temporary password: **{$autoGeneratedPassword}**";
                } else {
                    // CRITICAL: User creation failed. You might want to delete the staff record (roll back)
                    // You need to ensure your Staff class has a delete method that accepts the ID.
                    // $staff->deleteStaffRecord($staffId); 
                    $message = "❌ **CRITICAL FAILURE:** Staff record ID {$staffId} was saved, but failed to create user account. Error: " . $userCreationResult;
                }
            } else {
                $userMessage = "⚠️ Staff added successfully, but no email for user creation. Manual account setup needed.";
            }

        } else {
            // --- FAILURE PATH ---
            // staffId contains the error string (e.g., "❌ The email address is already...")
            $message = $staffId;
        }
    }
    
    // --- 2. Handle UPDATE Staff ---
    elseif (isset($_POST['update'])) {
        $data = [
            'staff_id'      => $_POST['staff_id'],
            'first_name'    => $_POST['staff_first_name'],
            'middle_init'   => $_POST['staff_middle_init'] ?? '',
            'last_name'     => $_POST['staff_last_name'],
            'phone'         => $_POST['staff_contact_num'],
            'email'         => $_POST['staff_email']
        ];
        // updateStaff returns a message string ("✅ Staff ID: X updated successfully." or "❌ Failed to update...")
        $message = $staff->updateStaff($data, $user_type);
    }
    
    // --- 3. Handle DELETE Staff ---
    elseif (isset($_POST['delete'])) {
        $id = $_POST['delete'];
        // deleteStaff returns a message string
        $message = $staff->deleteStaff($id, $user_type); 
    }
}


// --- Read Staff for Display (with Search) ---
if (!empty($search)) {
    $records = $staff->searchStaff($search, $user_type);
} else {
    $records = $staff->viewAllStaff($user_type); 
}

?>

<h1 class="fw-bold mb-4">Staff Management</h1>

<?php if ($message): ?>
<div class="alert <?= strpos($message, '❌') !== false ? 'alert-danger' : 'alert-info' ?>"><?= htmlspecialchars($message) ?></div>
<?php endif; ?>
<?php if ($userMessage): ?>
<div class="alert <?= strpos($userMessage, '⚠️') !== false ? 'alert-warning' : 'alert-success' ?>"><?= $userMessage ?></div>
<?php endif; ?>

<div class="d-flex justify-content-between align-items-center mb-3">
    <form class="d-flex" method="GET">
        <input type="hidden" name="module" value="staff">
        <input class="form-control me-2" type="search" name="search_staff" placeholder="Search by name or email..." value="<?= htmlspecialchars($search) ?>">
        <button class="btn btn-outline-primary" type="submit">Search</button>
        <?php if ($search): ?><a href="?module=staff" class="btn btn-outline-secondary ms-2">Reset</a><?php endif; ?>
    </form>
    <button class="btn btn-success" data-bs-toggle="collapse" data-bs-target="#addFormStaff">Add New Staff</button>
</div>

<div id="addFormStaff" class="collapse mb-4">
    <div class="card card-body shadow-sm">
        <form method="POST" class="row g-3">
            <div class="col-md-4"><input name="staff_first_name" class="form-control" placeholder="First Name" required></div>
            <div class="col-md-4"><input name="staff_middle_init" class="form-control" placeholder="Middle Initial"></div>
            <div class="col-md-4"><input name="staff_last_name" class="form-control" placeholder="Last Name" required></div>
            <div class="col-md-6"><input name="staff_contact_num" class="form-control" placeholder="Contact Number" required></div>
            <div class="col-md-6"><input type="email" name="staff_email" class="form-control" placeholder="Email (Used as Username)" required></div>
            
            <div class="col-md-12 text-end"><button name="add" class="btn btn-primary">Save Staff & Create User</button></div>
        </form>
    </div>
</div>

<div class="card p-3 shadow-sm">
    <h5>All Staff Records</h5>
    <div class="table-responsive">
        <table class="table table-bordered table-striped align-middle mt-3">
            <thead class="table-light">
                <tr>
                    <th>ID</th><th>First</th><th>Middle</th><th>Last</th>
                    <th>Contact</th><th>Email</th><th>Created</th><th>Updated</th><th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php if (empty($records)): ?>
                <tr><td colspan="9" class="text-center">No staff records found.</td></tr>
                <?php else: foreach ($records as $r): ?>
                <tr>
                    <form method="POST">
                        <td><?= $r['staff_id'] ?? '-' ?></td>
                        <td><input name="staff_first_name" value="<?= htmlspecialchars($r['first_name'] ?? '') ?>" class="form-control form-control-sm" required></td>
                        <td><input name="staff_middle_init" value="<?= htmlspecialchars($r['middle_init'] ?? '') ?>" class="form-control form-control-sm"></td>
                        <td><input name="staff_last_name" value="<?= htmlspecialchars($r['last_name'] ?? '') ?>" class="form-control form-control-sm" required></td>
                        <td><input name="staff_contact_num" value="<?= htmlspecialchars($r['phone'] ?? '') ?>" class="form-control form-control-sm" required></td>
                        <td><input type="email" name="staff_email" value="<?= htmlspecialchars($r['email'] ?? '') ?>" class="form-control form-control-sm" required></td>
                        <td><?= $r['created_at'] ?? '-' ?></td>
                        <td><?= $r['updated_at'] ?? '-' ?></td>
                        <td>
                            <input type="hidden" name="staff_id" value="<?= $r['staff_id'] ?? '' ?>">
                            <button name="update" class="btn btn-sm btn-success mb-1 w-100">Update</button>
                            <button name="delete" value="<?= $r['staff_id'] ?? '' ?>" class="btn btn-sm btn-danger w-100" onclick="return confirm('Delete this staff?')">Delete</button>
                        </td>
                    </form>
                </tr>
                <?php endforeach; endif; ?>
            </tbody>
        </table>
    </div>
</div>

<div class="modal fade" id="autoUserStaffModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered"><div class="modal-content">
        <div class="modal-header"><h5 class="modal-title">New User Account Created!</h5></div>
        <div class="modal-body">
            <p>A new staff record and linked user account were successfully created.</p>
            <p>Please note the temporary login details:</p>
            <div class="mb-3">
                <label>Linked Staff ID</label>
                <input type="text" class="form-control" value="<?= htmlspecialchars($displayStaffId ?? '') ?>" readonly>
            </div>
            <div class="mb-3">
                <label>Username (Email)</label>
                <input type="text" class="form-control" value="<?= htmlspecialchars($submittedEmail ?? '') ?>" readonly>
            </div>
            <div class="mb-3">
                <label>Temporary Password</label>
                <input type="text" class="form-control" value="<?= htmlspecialchars($autoGeneratedPassword) ?>" readonly>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
    </div></div>
</div>

<script>
<?php if($displayStaffId && !empty($autoGeneratedPassword)): ?>
document.addEventListener("DOMContentLoaded", function() {
    setTimeout(function() {
        var modal = new bootstrap.Modal(document.getElementById('autoUserStaffModal'));
        modal.show();
    }, 100);
});
<?php endif; ?>
</script>