<?php
// staff-module.php
require_once dirname(__DIR__, 3) . '/classes/Staff.php';
require_once dirname(__DIR__, 3) . '/classes/User.php';

// NOTE: $db, $_SESSION['user_type'], and formatDate() are assumed to be available.

$staff = new Staff($db);
$user = new User($db);
$message = '';
$userMessage = '';
$user_type = $_SESSION['user_type'] ?? '';
$search = $_GET['search_staff'] ?? '';
$newStaff = null;
$autoGeneratedPassword = '';
$displayStaffId = '';
$submittedEmail = '';

// --- ACCESS CONTROL (FIXED: Changed to match superadmin_dashboard.php) ---
if ($user_type !== 'superadmin') {
    echo '<div class="alert alert-danger">Access denied. Only Super Admin can access this module.</div>';
    return;
}

function generateRandomPassword($length = 10) {
    return substr(str_shuffle('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%'), 0, $length);
}


if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    
    // --- 1. Handle ADD (Create) Staff ---
    if (isset($_POST['add'])) {
        $data = [
            'first_name'    => trim($_POST['staff_first_name']),
            'middle_init'   => trim($_POST['staff_middle_init'] ?? ''),
            'last_name'     => trim($_POST['staff_last_name']),
            'phone'         => trim($_POST['staff_contact_num']),
            'email'         => trim($_POST['staff_email'] ?? '')
        ];
        
        // FIXED: Pass 'super_admin' to match Staff class expectations
        $staffId = $staff->create($data, 'super_admin'); 

        // Check for a valid positive integer ID
        if (is_numeric($staffId) && $staffId > 0) {
            // --- SUCCESS PATH ---
            $message = "✅ Staff added successfully with ID: {$staffId}.";
            $displayStaffId = $staffId;
            $submittedEmail = $data['email'];

            if (!empty($submittedEmail)) { 
                $autoGeneratedPassword = generateRandomPassword(10);
                $hashedPassword = password_hash($autoGeneratedPassword, PASSWORD_DEFAULT);
                
                $userData = [
                    'user_name' => $submittedEmail,
                    'password'  => $hashedPassword,
                    'linked_id' => $staffId,
                    'user_type' => 'staff'
                ];
                
                $userCreationResult = $user->addLinkedAccount($userData);
                
                if ($userCreationResult === true || (is_string($userCreationResult) && strpos($userCreationResult, '✅') !== false)) {
                    $userMessage = "✅ User account created for {$submittedEmail} with temporary password: <strong>{$autoGeneratedPassword}</strong>";
                } else {
                    $message = "⚠️ Staff record ID {$staffId} was saved, but failed to create user account. Error: " . htmlspecialchars($userCreationResult);
                }
            } else {
                $userMessage = "⚠️ Staff added successfully, but no email provided for user creation.";
            }

        } else {
            // --- FAILURE PATH ---
            $message = "❌ " . $staffId;
        }
    }
    
    // --- 2. Handle UPDATE Staff ---
    elseif (isset($_POST['update'])) {
        $data = [
            'staff_id'      => $_POST['staff_id'],
            'first_name'    => trim($_POST['staff_first_name']),
            'middle_init'   => trim($_POST['staff_middle_init'] ?? ''),
            'last_name'     => trim($_POST['staff_last_name']),
            'phone'         => trim($_POST['staff_contact_num']),
            'email'         => trim($_POST['staff_email'])
        ];
        // FIXED: Pass 'super_admin' to match Staff class expectations
        $message = $staff->update($data, 'super_admin');
    }
    
    // --- 3. Handle DELETE Staff ---
    elseif (isset($_POST['delete'])) {
        $id = $_POST['delete'];
        // FIXED: Pass 'super_admin' to match Staff class expectations
        $message = $staff->deleteStaff($id, 'super_admin'); 
    }
}


// --- Read Staff for Display (with Search) ---
if (!empty($search)) {
    $records = $staff->searchStaff($search, 'super_admin');
} else {
    $records = $staff->viewAllStaff('super_admin'); 
}

?>

<h1 class="fw-bold mb-4">Staff Management</h1>

<?php if ($message): ?>
<div class="alert <?= strpos($message, '❌') !== false || strpos($message, '⚠️') !== false ? 'alert-danger' : 'alert-info' ?>"><?= $message ?></div>
<?php endif; ?>
<?php if ($userMessage): ?>
<div class="alert <?= strpos($userMessage, '⚠️') !== false ? 'alert-warning' : 'alert-success' ?>"><?= $userMessage ?></div>
<?php endif; ?>

<div class="d-flex justify-content-between align-items-center mb-3">
    <form class="d-flex" method="GET">
        <input type="hidden" name="module" value="staff">
        <input class="form-control me-2" type="search" name="search_staff" placeholder="Search by name or email..." value="<?= htmlspecialchars($search) ?>">
        <button class="btn btn-outline-primary" type="submit">Search</button>
        <?php if ($search): ?><a href="?module=staff" class="btn btn-outline-secondary ms-2">Reset</a><?php endif; ?>
    </form>
    <button class="btn btn-success" data-bs-toggle="collapse" data-bs-target="#addFormStaff">+ Add New Staff</button>
</div>

<div id="addFormStaff" class="collapse mb-4">
    <div class="card card-body shadow-sm">
        <form method="POST" class="row g-3">
            <div class="col-md-4"><input name="staff_first_name" class="form-control" placeholder="First Name *" required></div>
            <div class="col-md-4"><input name="staff_middle_init" class="form-control" placeholder="Middle Initial"></div>
            <div class="col-md-4"><input name="staff_last_name" class="form-control" placeholder="Last Name *" required></div>
            <div class="col-md-6"><input name="staff_contact_num" class="form-control" placeholder="Contact Number *" required></div>
            <div class="col-md-6"><input type="email" name="staff_email" class="form-control" placeholder="Email (Username) *" required></div>
            
            <div class="col-md-12 text-end"><button name="add" class="btn btn-primary">💾 Save Staff & Create User Account</button></div>
        </form>
    </div>
</div>

<div class="card p-3 shadow-sm">
    <h5 class="mb-0">All Staff Records (<?= count($records) ?>)</h5>
    <div class="table-responsive mt-3" style="overflow-x: auto;">
        <table class="table table-bordered table-striped table-hover align-middle" style="min-width: 1200px;">
            <thead class="table-dark">
                <tr>
                    <th style="width: 60px;">ID</th>
                    <th>First Name</th>
                    <th style="width: 100px;">M.I.</th>
                    <th>Last Name</th>
                    <th>Contact</th>
                    <th>Email</th>
                    <th>Created</th>
                    <th>Updated</th>
                    <th style="width: 140px;">Action</th>
                </tr>
            </thead>
            <tbody>
                <?php if (empty($records)): ?>
                <tr><td colspan="9" class="text-center text-muted py-4">No staff records found.</td></tr>
                <?php else: foreach ($records as $r): ?>
                <tr>
                    <form method="POST">
                        <td class="text-center"><?= $r['staff_id'] ?? '-' ?></td>
                        <td><input name="staff_first_name" value="<?= htmlspecialchars($r['first_name'] ?? '') ?>" class="form-control form-control-sm" required></td>
                        <td><input name="staff_middle_init" value="<?= htmlspecialchars($r['middle_init'] ?? '') ?>" class="form-control form-control-sm"></td>
                        <td><input name="staff_last_name" value="<?= htmlspecialchars($r['last_name'] ?? '') ?>" class="form-control form-control-sm" required></td>
                        <td><input name="staff_contact_num" value="<?= htmlspecialchars($r['phone'] ?? '') ?>" class="form-control form-control-sm" required></td>
                        <td><input type="email" name="staff_email" value="<?= htmlspecialchars($r['email'] ?? '') ?>" class="form-control form-control-sm" required></td>
                        <td class="text-center small"><?= $r['created_at'] ?? '-' ?></td>
                        <td class="text-center small"><?= $r['updated_at'] ?? '-' ?></td>
                        <td>
                            <input type="hidden" name="staff_id" value="<?= $r['staff_id'] ?? '' ?>">
                            <button name="update" class="btn btn-sm btn-success mb-1 w-100">✏️ Update</button>
                            <button name="delete" value="<?= $r['staff_id'] ?? '' ?>" class="btn btn-sm btn-danger w-100" onclick="return confirm('⚠️ Delete this staff member and their user account?')">🗑️ Delete</button>
                        </td>
                    </form>
                </tr>
                <?php endforeach; endif; ?>
            </tbody>
        </table>
    </div>
</div>

<!-- Modal for displaying auto-generated credentials -->
<div class="modal fade" id="autoUserStaffModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered"><div class="modal-content">
        <div class="modal-header bg-success text-white">
            <h5 class="modal-title">✅ New User Account Created!</h5>
            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body">
            <p class="lead">A new staff record and linked user account were successfully created.</p>
            <p class="text-danger"><strong>⚠️ Important:</strong> Please save these credentials securely. The password will not be shown again.</p>
            <div class="mb-3">
                <label class="form-label fw-bold">Staff ID</label>
                <input type="text" class="form-control" value="<?= htmlspecialchars($displayStaffId ?? '') ?>" readonly>
            </div>
            <div class="mb-3">
                <label class="form-label fw-bold">Username (Email)</label>
                <input type="text" class="form-control" value="<?= htmlspecialchars($submittedEmail ?? '') ?>" readonly>
            </div>
            <div class="mb-3">
                <label class="form-label fw-bold">Temporary Password</label>
                <div class="input-group">
                    <input type="text" id="tempPassword" class="form-control" value="<?= htmlspecialchars($autoGeneratedPassword) ?>" readonly>
                    <button class="btn btn-outline-secondary" type="button" onclick="copyPassword()">📋 Copy</button>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">I've Saved the Credentials</button>
        </div>
    </div></div>
</div>

<script>
<?php if($displayStaffId && !empty($autoGeneratedPassword)): ?>
document.addEventListener("DOMContentLoaded", function() {
    setTimeout(function() {
        var modal = new bootstrap.Modal(document.getElementById('autoUserStaffModal'));
        modal.show();
    }, 100);
});
<?php endif; ?>

function copyPassword() {
    const passwordInput = document.getElementById('tempPassword');
    passwordInput.select();
    document.execCommand('copy');
    alert('Password copied to clipboard!');
}
</script>